server:
  port: 8084
  address: 0.0.0.0

spring:
  application:
    name: itemservice
  datasource:
    url: jdbc:mysql://172.24.116.171:3307/hmdp?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  # ✅ 层级正确，且属性名按 Spring Boot 3.x 规范
  data:
    redis:
      host: 172.24.116.171
      port: 6379
      database: 6
      password: Cjx200621
      timeout: 3000ms
      lettuce:
        pool:
          max-active: 10
          max-idle: 5
          min-idle: 2


canal:
  # wsl的canal‑deployer  tcp地址端口
  server: 172.24.116.171:11111
  # destination 实例名字，和你在admin网页新建的instance名称保持一致，默认填example
  destination: information
